CREATE SEQUENCE IF NOT EXISTS T_BOOK_STORE_SEQ START 1 INCREMENT BY 1;

CREATE TABLE T_BOOK_STORE (
 ID INTEGER DEFAULT nextval('T_BOOK_STORE_SEQ'),
 BOOK_NAME VARCHAR(200),
 AUTHOR_NAME VARCHAR(200),
 PUBLISHER_NAME VARCHAR(200),
 CREATED_BY VARCHAR(100),
 CREATED_AT TIMESTAMP(2),
 UPDATED_BY VARCHAR(100),
 UPDATED_AT TIMESTAMP(2),
 PRIMARY KEY (BOOK_NAME)
);